### ISSUE TITLE
Sigh print 2 times instead of one

### ISSUE THREAD

**Issue by tgregoir-oss** [norswap/sigh#8] opened 2022-05-17 19:00 UTC
When we execute this code on Sigh, the word "oui" is printed twice :
String def a(){
    print("oui")
    return "non"
}
print(a())

*You will have to adapt the code because we modified the grammar in our version of Sigh*

Before writing this post, we tested and found this bug/problem on 3 different "projects". One with a basic version of Sigh. One with some new features on Sigh, and another time on another version of Sigh with other kinds of features. We don’t have any idea about the origin of the problem.

**Comment by norswap** [comment] 2022-05-22 02:39
The problem is here: https://github.com/norswap/sigh/blame/master/src/norswap/sigh/interpreter/Interpreter.java#L401-L402

The first of these two lines is redundant with the second one and means that every function argument is evaluated twice!

Nice catch 👍

**Comment by norswap** [comment] 2022-05-22 03:20
Fixed by https://github.com/norswap/sigh/commit/bbf45ed80f794fda9b2406fe7a35bdaa8e625947

**Closed as completed by norswap** 2022-05-22 03:20 UTC
